# Generated by Django 5.0.7 on 2024-10-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commune', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messaegmodel',
            name='receiver_pfp',
            field=models.FileField(blank=True, null=True, upload_to='message_pfps'),
        ),
    ]
