# Generated by Django 5.0.7 on 2024-10-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commune', '0002_messaegmodel_receiver_pfp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messaegmodel',
            name='receiver_pfp',
        ),
        migrations.AddField(
            model_name='threadmodel',
            name='receiver_pfp',
            field=models.FileField(blank=True, null=True, upload_to='thread_pfps'),
        ),
    ]
