# Generated by Django 5.0.7 on 2024-11-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commune', '0004_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadmodel',
            name='receiver_pfp',
            field=models.ImageField(blank=True, null=True, upload_to='thread_pfps'),
        ),
    ]
